In [ ]:
import os
import glob
import re
import numpy as np
from scipy import sparse
import gc
from scipy.sparse import csr_matrix
from scipy.sparse import vstack
import pickle
import pandas as pd
from tqdm import tqdm
from nltk.util import ngrams
os.chdir(r'D:\Applied_AI\refrence for assignment 16\train')

In [ ]:
import psutil
psutil.virtual_memory()

In [3]:
from sklearn.feature_extraction.text import TfidfVectorizer
vectorizer = TfidfVectorizer(ngram_range=(2,2))

In [4]:
bytes_files = glob.glob('*.bytes')
asm_files = glob.glob('*.bytes')
len(bytes_files),type(bytes_files),len(asm_files),type(asm_files)

In [5]:
def byt_preprocess(st,end):

    chunk = []
    for file in tqdm(range(st,end)):
        with(open(bytes_files[file],'r')) as fl:
            a = fl.read()
            b = re.sub(r'\?','x',a)
            c = [re.sub(r'\n|\b\w{3,10}\b','',b).strip()]  
            chunk.append(vectorizer.fit_transform(c))

In [ ]:
chunk0 = byt_preprocess(0,2000)

In [6]:
pickle.dump(chunk0,open(r'D:\Applied_AI\data\pickled\txt0','wb'))

In [ ]:
chunk1 = byt_preprocess(2000,4000)

In [ ]:
pickle.dump(chunk1,open(r'D:\Applied_AI\data\pickled\txt1','wb'))

In [ ]:
chunk2 = byt_preprocess(4000,6000)

In [ ]:
pickle.dump(chunk2,open(r'D:\Applied_AI\data\pickled\txt2','wb'))

In [ ]:
chunk3 = byt_preprocess(6000,8000)

In [ ]:
pickle.dump(chunk3,open(r'D:\Applied_AI\data\pickled\txt3','wb'))

In [ ]:
chunk4 = byt_preprocess(8000,10000)

In [ ]:
pickle.dump(chunk4,open(r'D:\Applied_AI\data\pickled\txt4','wb'))

In [ ]:
chunk5 = byt_preprocess(10000,len(bytes_files))

In [ ]:
pickle.dump(chunk5,open(r'D:\Applied_AI\data\pickled\txt5','wb'))

In [29]:
os.chdir(r'D:\Applied_AI\data\pickled')

In [30]:
chunk0=pickle.load(open('txt0','rb'))
chunk1=pickle.load(open('txt1','rb'))
chunk2=pickle.load(open('txt2','rb'))
chunk3=pickle.load(open('txt3','rb'))
chunk4=pickle.load(open('txt4','rb'))
chunk5=pickle.load(open('txt5','rb'))

In [32]:
length = []
for i in range(len(chunk0)):
    length.append(chunk0[i].shape[1])
for i in range(len(chunk1)):
    length.append(chunk1[i].shape[1])
for i in range(len(chunk2)):
    length.append(chunk2[i].shape[1])
for i in range(len(chunk3)):
    length.append(chunk3[i].shape[1])
for i in range(len(chunk4)):
    length.append(chunk4[i].shape[1])
for i in range(len(chunk5)):
    length.append(chunk5[i].shape[1])

In [33]:
a=sorted(length)

In [34]:
p10 = int(np.percentile(a,10))
p20 = int(np.percentile(a,20))
p30 = int(np.percentile(a,30))
p40 = int(np.percentile(a,40))
p50 = int(np.percentile(a,50))
p60 = int(np.percentile(a,60))
p70 = int(np.percentile(a,70))
p80 = int(np.percentile(a,80))
p90 = int(np.percentile(a,90))
p100 = int(np.percentile(a,100))

In [35]:
y = [p10,p20,p30,p40,p50,p60,p70,p80,p90,p100]
x = [10,20,30,40,50,60,70,80,90,100]

In [36]:
import matplotlib.pyplot as plt
plt.plot(y,x)
plt.grid()

In [37]:
fin_len = p60
fin_len

In [38]:
csr_frmt = [*chunk0,*chunk1,*chunk2,*chunk3,*chunk4,*chunk5]

In [39]:
del chunk0
del chunk1
del chunk2
del chunk3
del chunk4
del chunk5
gc.collect()

In [40]:
os.chdir(r'D:\Applied_AI\data\pickled')

In [42]:
fin_mat = []
for i in range(len(bytes_files)):
    x = csr_frmt[i].toarray()[0]
    if len(x)>=fin_len:
        fin_mat.append(sparse.csr_matrix(x[:fin_len]))
    else:
        fin_mat.append(sparse.csr_matrix(np.pad(x,(0,(fin_len-len(x))))))

In [43]:
matrix = vstack(fin_mat)

In [44]:
matrix.shape

In [45]:
pickle.dump(matrix,open('bytes_file_matrix','wb'))

In [46]:
del matrix
gc.collect()

In [48]:
os.chdir(r'D:\Applied_AI\data\pickled')

In [49]:
mat = pickle.load(open('bytes_file_matrix','rb'))

In [54]:
a = mat.toarray()
a.shape

(10868, 59043)

In [55]:
df = pd.DataFrame(a)

In [56]:
df.head()

,0,1,2,3,4,5,6,7,8,9,...,59033,59034,59035,59036,59037,59038,59039,59040,59041,59042
0,0.994032,0.004597,0.003727,0.005321,0.004444,0.004144,0.005205,0.004575,0.004253,0.004600,...,0.000022,0.000036,0.000025,0.000014,0.000029,0.000014,0.000007,0.000018,0.000014,0.000011
1,0.130002,0.004639,0.000450,0.000296,0.001079,0.000074,0.000062,0.000068,0.000259,0.000056,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
2,0.213909,0.007590,0.002025,0.001834,0.006533,0.007577,0.007093,0.001859,0.006724,0.001961,...,0.000064,0.000089,0.000025,0.000051,0.000076,0.000102,0.000420,0.000076,0.000076,0.000025
3,0.591020,0.012766,0.003461,0.003915,0.006468,0.002269,0.001418,0.001248,0.003574,0.000851,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
4,0.860497,0.003279,0.001163,0.006664,0.000476,0.000582,0.000159,0.000264,0.000582,0.000159,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000

In [59]:
os.chdir(r'D:\Applied_AI\refrence for assignment 16')
label = pd.read_csv('trainLabels.csv')

In [61]:
df.insert(0,'ID',label['Id'],True)
df.insert(1,'Class',label['Class'],True)

In [62]:
df.head(3)

,ID,Class,0,1,2,3,4,5,6,7,...,59033,59034,59035,59036,59037,59038,59039,59040,59041,59042
0,01kcPWA9K2BOxQeS5Rju,1,0.994032,0.004597,0.003727,0.005321,0.004444,0.004144,0.005205,0.004575,...,0.000022,0.000036,0.000025,0.000014,0.000029,0.000014,0.000007,0.000018,0.000014,0.000011
1,04EjIdbPV5e1XroFOpiN,1,0.130002,0.004639,0.000450,0.000296,0.001079,0.000074,0.000062,0.000068,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
2,05EeG39MTRrI6VY21DPd,1,0.213909,0.007590,0.002025,0.001834,0.006533,0.007577,0.007093,0.001859,...,0.000064,0.000089,0.000025,0.000051,0.000076,0.000102,0.000420,0.000076,0.000076,0.000025

In [63]:
pickle.dump(df,open('D:\Applied_AI\data\pickled\df','wb'))